name: CD - Terraform Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Save EC2 Private Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > hello.pem
          chmod 400 hello.pem

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get EC2 Public IP Output
        id: get_ip
        run: |
          echo "PUBLIC_IP=$(terraform -chdir=./terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Output Access URL
        run: |
          echo "Strapi should be available at: http://${{ env.PUBLIC_IP }}:1337"
